### ISSUE TITLE
Exporting items with PMID or PMCID in the Extra field

### ISSUE THREAD

**Issue by richardkaplan** [retorquere/zotero-seektable-export#2]
Consider these 2 test cases and look at the Extra fields:

https://www.zotero.org/rkaplanumrpc.com/items/itemKey/FQG4LUTJ

https://www.zotero.org/rkaplanumrpc.com/items/itemKey/RSCLPY2I

When exporting to CSV an item that has both a PMID and PMCID in the Extra field, please put the corresponding PubMed Central URL into the URL field such as:

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5769319/

When syncing an item that has a PMID but not a PMCID in the Extra field, please put the corresponding PubMed URL into the URL field such as:

https://www.ncbi.nlm.nih.gov/pubmed/7268543

**Comment by retorquere** [comment]
I don't have access to those urls.

**Comment by richardkaplan** [comment]
You can reproduce those by going to the two nlm.nih.gov URLs above and importing them with the default translator

![image](https://user-images.githubusercontent.com/6059733/56110317-fb870480-5f21-11e9-9144-e0dfe863476d.png)

![image](https://user-images.githubusercontent.com/6059733/56110324-0772c680-5f22-11e9-88a8-3ea4b2c3eda5.png)

**Comment by retorquere** [comment]
I don't get it. As per #1, you said you wanted those `extra` fields to be treated as if they were empty.

**Comment by richardkaplan** [comment]
Yes I do want those fields to be treated as empty because I am using that field for another purpose.

But I realized some odd behavior in how Zotero treats some PubMed entries.   Take for example the "1980 Volvo award winner" article above - there is neither a URL nor a DOI in the Zotero database.  Somehow Zotero is able to open the article online, but I have no URL to  open the article from either my Sync database or my CSV database.  I am not sure how Zotero does that but I have found a good number of examples like this.  Oddly there are imported through the PubMed translator but the PubMed translator does not add the PubMed URL in these cases but it does add the PMID: and/or PMCID: to the Extra field.

So a fix is when Sync or CSV Export is run, if a PMID: or PMCID: is in the Extra field, then first update the URL field, and thereafter ignore the PMID: or PMCID: fields.

I might choose at some point to use a different field other than Extra.  Or maybe eventually Zotero will add custom user fields.    But even then, the problem will exist that there are records imported with no DOI and no URL.  So creating that info from the Extra field will always be important.

**Comment by retorquere** [comment]
And this should replace any URL that's already there? Because if I import the first link, the URL field is filled.

**Comment by richardkaplan** [comment]
On further thought, order of preference (most preferable to least) should be:

1 - Existing URL, if present

2 - Pubmed Central URL, if available via PMCID information

3.  Pubmed URL, if available via PMID information

**Comment by retorquere** [comment]
Previously you said that if an URL isn't present, but a DOI is, I should fill the URL field with a DOI URL. Where does that sit in this order?

**Comment by richardkaplan** [comment]
Doi url is above pmid if we have it

On Apr 15, 2019, at 12:14 PM, Emiliano Heyns <notifications@github.com<mailto:notifications@github.com>> wrote:


Previously you said that if an URL isn't present, but a DOI is, I should fill the URL field with a DOI URL. Where does that sit in this order?

**Comment by retorquere** [comment]
0.0.17 has it.

**Comment by richardkaplan** [comment]
Thanks
On Apr 15, 2019, at 12:27 PM, Emiliano Heyns <notifications@github.com<mailto:notifications@github.com>> wrote:


0.0.17 has it.
