### ISSUE TITLE
Parent Collections is Incomplete

### ISSUE THREAD

**Issue by richardkaplan** [retorquere/zotero-seektable-export#3]
Consider the situation when I export "For Publication" non-bundled:

![image](https://user-images.githubusercontent.com/6059733/56191296-1b89f700-5ffa-11e9-954c-a7702b3311e9.png)

Why is the parent collection "For Publication" missing for items in Volvo Award Winners?

![image](https://user-images.githubusercontent.com/6059733/56191364-38bec580-5ffa-11e9-9c5d-eee795d623ea.png)

See CSV attached

[For Publication.csv.zip](https://github.com/retorquere/zotero-seektable-export/files/3083598/For.Publication.csv.zip)

**Comment by retorquere** [comment]
Because Zotero doesn't pass that information to translators. The collection being exported itself is just considered "the root" when zotero exports it, and it's name, or even the face that only a part of the library is exported, is not information that's available to translators.

**Comment by richardkaplan** [comment]
Thanks - solved
